trigger:
  - none

stages:
  - stage: build
    displayName: Build
    jobs:
      - template: pipeline-templates/jobs-build-and-test.yml
        parameters:
          artifactName: "webapp"
          projectPath: "**/src/**/Web.csproj"
          functionalTestProjectPath: "tests/Application.FunctionalTests/Application.FunctionalTests.csproj"
          appUnitTestProjectPath: "tests/Application.UnitTests/Application.UnitTests.csproj"
          domainUnitTestProjectPath: "tests/Domain.UnitTests/Domain.UnitTests.csproj"
          infrastructureIntegrationTestProjectPath: "tests/Infrastructure.IntegrationTests/Infrastructure.IntegrationTests.csproj"
          webAcceptanceTestProjectPath: "tests/Web.AcceptanceTests/Web.AcceptanceTests.csproj"
  # - template: pipeline-templates/stage-deploy.yml
  #   parameters:
  #     environments:
  #       - {
  #           name: "Dev",
  #           dependsOn: build,
  #           runOnProdBranch: false,
  #           keyvaultName: "kv-SmartFleetPOC-dev",
  #         }
  #       - {
  #           name: "Test",
  #           dependsOn: build,
  #           runOnProdBranch: true,
  #           keyvaultName: "kv-SmartFleetPOC-test",
  #         }
  #       - {
  #           name: "Prod",
  #           dependsOn: deploy_test,
  #           runOnProdBranch: true,
  #           keyvaultName: "kv-SmartFleetPOC-prod",
  #         }
